Repository cs169/lamorinda-spirit-van, pull requests merged in 2025-04, with the labels that each got.

#89 87 adding more cucumber tests for rides passesngers rspec tests for duplicate addresses
  Gemfile
  Gemfile.lock
  features/crud_passengers.feature
  features/homepage.feature
  features/step_definitions/crud_passengers_steps.rb
  features/step_definitions/homepage_steps.rb
  features/support/env.rb
  features/support/hooks.rb
  spec/models/passenger_spec.rb
Labels: points: 1, 💎 testing

#77 75 feat shift calendar for drivers
  .DS_Store
  app/assets/stylesheets/rides.css
  app/controllers/drivers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/models/ride.rb
  app/views/drivers/_driver.html.erb
  app/views/drivers/all_shifts.html.erb
  app/views/drivers/today.html.erb
  app/views/rides/filter.html.erb
  app/views/rides/show.html.erb
  app/views/rides/today.html.erb
  app/views/shifts/_form.html.erb
  app/views/shifts/feedback.html.erb
  app/views/shifts/index.html.erb
  app/views/shifts/read_only.html.erb
  app/views/shifts/show.html.erb
  config/routes.rb
  db/fake_rides_data.csv
  db/migrate/20250320232838_add_feedback_to_shifts.rb
  db/schema.rb
  features/dispatcher/dispatcher_shift_creation.feature
  features/dispatcher/dispatcher_shift_navigation.feature
  features/driver/driver_shift_navigation.feature
  features/shifts_navigation.feature
  features/step_definitions/dispatcher_data_setup_steps.rb
  features/step_definitions/dispatcher_shift_steps.rb
  features/step_definitions/driver_shift_steps.rb
  features/step_definitions/shared_navigation_steps.rb
  features/step_definitions/shifts_navigation_steps.rb
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/models/ride_spec.rb
Labels: enhancement, points: 1

#79 76 feat shift feedback system
  app/assets/stylesheets/rides.css
  app/controllers/drivers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/models/ride.rb
  app/views/drivers/_driver.html.erb
  app/views/drivers/today.html.erb
  app/views/rides/filter.html.erb
  app/views/rides/today.html.erb
  app/views/shifts/_form.html.erb
  app/views/shifts/feedback.html.erb
  config/routes.rb
  db/fake_rides_data.csv
  db/migrate/20250320232838_add_feedback_to_shifts.rb
  features/dispatcher/dispatcher_shift_creation.feature
  features/dispatcher/dispatcher_shift_navigation.feature
  features/driver/driver_shift_navigation.feature
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/models/ride_spec.rb
Labels: enhancement, points: 1, ⚠️ migration required

#90 58 structure driver login system
  Gemfile
  app/controllers/admin/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/models/ride.rb
  app/models/shift.rb
  app/models/user.rb
  app/views/admin/users/edit.html.erb
  app/views/admin/users/index.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/drivers/_driver.html.erb
  app/views/layouts/application.html.erb
  app/views/rides/show.html.erb
  app/views/shifts/read_only.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20250326230417_devise_create_users.rb
  db/migrate/20250326230439_add_role_to_users.rb
  db/seeds.rb
  features/crud_passengers.feature
  features/dispatcher/dispatcher_shift_creation.feature
  features/dispatcher/dispatcher_shift_navigation.feature
  features/driver/driver_shift_navigation.feature
  features/step_definitions/crud_passengers_steps.rb
  features/step_definitions/driver_shift_steps.rb
  features/step_definitions/shared_navigation_steps.rb
  features/step_definitions/user_authentication_steps.rb
  features/user_authentication.feature
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/passengers_controller_spec.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/factories/users.rb
  spec/models/ride_spec.rb
  spec/models/shift_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: enhancement, points: 2, ⚠️ migration required, 🏗️ infrastructure

#93 Added header with nav bar, footer, global container
  .DS_Store
  app/assets/images/lamorindalogo.png
  app/assets/stylesheets/application.css
  app/views/drivers/_form.html.erb
  app/views/drivers/edit.html.erb
  app/views/drivers/index.html.erb
  app/views/drivers/new.html.erb
  app/views/layouts/application.html.erb
  app/views/passengers/_form.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/passengers/edit.html.erb
  app/views/passengers/index.html.erb
  app/views/passengers/new.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/filter.html.erb
  app/views/rides/index.html.erb
  app/views/rides/new.html.erb
  config/routes.rb
Labels: enhancement, points: 1

#91 59 assign rides passenger autocomplete
  .github/workflows/ci.yml
  Gemfile
  app/controllers/rides_controller.rb
  app/javascript/application.js
  app/javascript/autocomplete.js
  app/views/layouts/application.html.erb
  app/views/rides/new.html.erb
  features/dispatcher/dispatcher_shift_creation.feature
  features/dispatcher/dispatcher_shift_navigation.feature
  features/driver/driver_shift_navigation.feature
  features/new_ride_autocomplete.feature
  features/step_definitions/crud_passengers_steps.rb
  features/step_definitions/driver_shift_steps.rb
  features/step_definitions/factory_steps.rb
  features/step_definitions/shared_navigation_steps.rb
  features/step_definitions/web_steps.rb
  features/support/env.rb
  features/support/paths.rb
Labels: enhancement, points: 1, 💡research needed

#83 [feat] 61 Added Column-Specific Searching for DataTables
  app/javascript/application.js
  db/fake_rides_data.csv
Labels: enhancement, points: 1

#96 71 update shift timeline uand ride assignments
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/views/shifts/_shift_rides.html.erb
  app/views/shifts/show.html.erb
  db/migrate/20250408034142_add_notes_to_shift.rb
  db/seeds.rb
  spec/controllers/shifts_controller_spec.rb
Labels: enhancement, points: 1

#94 84 feat role specific views
  app/controllers/admin/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/drivers_controller.rb
  app/controllers/passengers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/helpers/application_helper.rb
  app/models/user.rb
  app/views/drivers/today.html.erb
  app/views/layouts/application.html.erb
  app/views/shifts/index.html.erb
  app/views/shifts/read_only.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  config/routes.rb
  features/dispatcher/dispatcher_shift_creation.feature
  features/dispatcher/dispatcher_shift_navigation.feature
  features/driver/driver_shift_navigation.feature
  features/step_definitions/crud_passengers_steps.rb
  features/step_definitions/user_authentication_steps.rb
  features/support/paths.rb
  features/user_authentication.feature
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/user_auth_spec.rb
Labels: enhancement, points: 1

#116 97 feat report generation page
  Gemfile
  Gemfile.lock
  app/views/layouts/_flash.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/blazer/application.html.erb
  blazer_queries.yml
  config/blazer.yml
  config/database.yml
  config/routes.rb
  db/migrate/20250411004038_install_blazer.rb
  lib/tasks/blazer_backup.rake
Labels: enhancement

#104 42 Login with Microsoft
  Gemfile
  Gemfile.lock
  app/assets/images/ms-symbollockup_signin_light.png
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/shared/_links.html.erb
  config/credentials.yml.enc
  config/initializers/devise.rb
  config/routes.rb
  spec/features/omniauth_sign_in_spec.rb
  spec/rails_helper.rb
  spec/requests/omniauth_callbacks_spec.rb
  spec/support/omniauth.rb
Labels: enhancement, points: 1, 👀 accessibility

#114 105 New Accessbility Fields For Rides and Passengers Table
  Gemfile
  app/javascript/datatables.js
  app/views/layouts/blazer/application.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/rides/_ride.html.erb
  db/dont_use_fake_rides_data.csv
  db/fake_passengers.csv
  db/fake_passengers_data.csv
  db/fake_rides_data.csv
  db/migrate/20250414055406_add_accessibility_fields_to_rides_and_passengers.rb
  db/migrate/20250416225911_remove_new_passenger_field_from_rides_and_passengers.rb
  lib/tasks/02_import_fake_passengers.rake
  lib/tasks/03_import_fake_rides.rake
  lib/tasks/import.rake
  lib/tasks/setup_and_import.rake
Labels: points: 1, ⚠️ migration required, 🏗️ infrastructure

#117 99 Show Driver Ride Info
  app/views/rides/show.html.erb
Labels: enhancement, points: 1

#113 85 feat password reset emails
  app/mailers/application_mailer.rb
  app/views/drivers/index.html.erb
  app/views/drivers/today.html.erb
  config/environments/production.rb
  config/initializers/devise.rb
Labels: enhancement, points: 1

#119 74 feat ride feedback system
  app/controllers/feedbacks_controller.rb
  app/controllers/rides_controller.rb
  app/helpers/feedbacks_helper.rb
  app/javascript/datatables.js
  app/models/feedback.rb
  app/models/ride.rb
  app/views/drivers/today.html.erb
  app/views/feedbacks/_feedback.html.erb
  app/views/feedbacks/_feedback.json.jbuilder
  app/views/feedbacks/_form.html.erb
  app/views/feedbacks/edit.html.erb
  app/views/feedbacks/index.html.erb
  app/views/feedbacks/index.json.jbuilder
  app/views/feedbacks/new.html.erb
  app/views/feedbacks/show.html.erb
  app/views/feedbacks/show.json.jbuilder
  app/views/rides/_ride.html.erb
  config/routes.rb
  db/migrate/20250417221035_create_feedbacks.rb
  db/migrate/20250417221441_add_ride_to_feedbacks.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/factories/feedbacks.rb
Labels: enhancement, points: 1, ⚠️ migration required, 🏗️ infrastructure

#118 106 feat link user and driver through email
  app/controllers/drivers_controller.rb
  app/views/drivers/today.html.erb
  db/seed_data.rb
  db/seeds.rb
  spec/controllers/drivers_controller_spec.rb
Labels: enhancement, points: 1

#121 101 allow admin to delete all users with no assigned role
  app/controllers/admin/users_controller.rb
  app/views/admin/users/index.html.erb
  app/views/drivers/index.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
  spec/controllers/admin/users_controller_spec.rb
Labels: enhancement, points: 1

#122 100 feat timeline on today page
  app/assets/stylesheets/shifts.css
  app/views/drivers/today.html.erb
  app/views/shifts/_shift.html.erb
  db/schema.rb
Labels: enhancement, points: 1
