Repository cs169/lamorinda-spirit-van, pull requests merged in 2025-06, with the labels that each got.

#140 133 Update Rides and Addresses
  .byebug_history
  Gemfile
  Gemfile.lock
  app/controllers/drivers_controller.rb
  app/controllers/feedbacks_controller.rb
  app/controllers/passengers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/javascript/autocomplete.js
  app/models/address.rb
  app/models/ride.rb
  app/views/drivers/today.html.erb
  app/views/feedbacks/_form.html.erb
  app/views/passengers/_form.html.erb
  app/views/rides/_form.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/_stop_fields.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/new.html.erb
  app/views/rides/show.html.erb
  app/views/shifts/_shift_rides.html.erb
  db/fake_addresses_lamorinda.csv
  db/fake_rides_data.csv
  db/migrate/20250507202923_update_rides_and_addresses.rb
  db/schema.rb
  features/crud_passengers.feature
  features/step_definitions/crud_passengers_steps.rb
  lib/tasks/01_import_fake_addresses.rake
  lib/tasks/03_import_fake_rides.rake
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/factories/addresses.rb
  spec/factories/rides.rb
  spec/models/passenger_spec.rb
  spec/models/ride_spec.rb
Labels: points: 1, ⚠️ migration required

#158 update CI
  .github/workflows/ci.yml
  docs/docs/Advanced Tips/1.Quick Homepage Access/Quick Homepage Access.md
Labels: enhancement

#164 fix ride, automatically create Feedback on Ride creation
  app/models/ride.rb
  spec/models/ride_spec.rb
Labels: bug

#161 160 enhance usability
  .gitignore
  ENCRYPTION_README.md
  app/controllers/rides_controller.rb
  app/javascript/autocomplete.js
  app/javascript/datatables.js
  app/models/address.rb
  app/views/drivers/today.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/rides/_ride.html.erb
  app/views/shifts/_shift_rides.html.erb
  db/fake_rides_data.csv
  db/migrate/20250611082827_change_lmv_member_to_boolean.rb
  db/migrate/20250612094229_add_source_to_rides_and_shifts.rb
  db/schema.rb
  db/seed_data.rb
  db/seeds.rb
  lib/tasks/01_import_fake_addresses.rake
  lib/tasks/03_import_fake_rides.rake
  lib/tasks/import.rake
  lib/tasks/import_data.rake
  lib/tasks/import_drivers.rake
  lib/tasks/import_passengers.rake
  lib/tasks/import_rides.rake
  spec/factories/addresses.rb
  spec/models/address_spec.rb
  spec/models/ride_spec.rb
Labels: enhancement

#165 Uses ruby's include() for retrival to prevent n+1 queries
  app/controllers/drivers_controller.rb
  app/controllers/passengers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  lib/tasks/import.rake
Labels: chore

#172 168 update report generation, export as excel sheet, update rides/pass columns
  app/assets/stylesheets/application.css
  app/assets/stylesheets/datatables_custom.css
  app/controllers/application_controller.rb
  app/controllers/drivers_controller.rb
  app/controllers/feedbacks_controller.rb
  app/controllers/passengers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/javascript/autocomplete.js
  app/javascript/datatables.js
  app/models/ride.rb
  app/views/feedbacks/_form.html.erb
  app/views/layouts/application.html.erb
  app/views/passengers/_form.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/passengers/index.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/new.html.erb
  app/views/rides/show.html.erb
  blazer_queries.yml
  db/migrate/20250628065723_replace_low_income_with_fare_type.rb
  db/migrate/20250628212856_change_date_time_backto_date.rb
  db/schema.rb
  features/step_definitions/crud_passengers_steps.rb
  lib/tasks/import.rake
  lib/tasks/import_rides.rake
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/factories/rides.rb
  spec/models/ride_spec.rb
Labels: enhancement
