Repository cs169/lamorinda-spirit-van, pull requests merged in 2025-02, with the labels that each got.

#2 Update index.html.erb - Daniel
  app/views/posts/index.html.erb
Labels: chore

#4 Update index.html.erb - Chang
  app/views/posts/index.html.erb
Labels: chore

#7 Update index.html.erb
  app/views/posts/index.html.erb
Labels: chore

#10 Update index.html.erb
  app/views/posts/index.html.erb
Labels: points: 1, chore

#25 18 structure driver model
  .DS_Store
  .gitignore
  app/controllers/drivers_controller.rb
  app/helpers/drivers_helper.rb
  app/models/.DS_Store
  app/models/driver.rb
  app/views/drivers/_driver.html.erb
  app/views/drivers/_driver.json.jbuilder
  app/views/drivers/_form.html.erb
  app/views/drivers/edit.html.erb
  app/views/drivers/index.html.erb
  app/views/drivers/index.json.jbuilder
  app/views/drivers/new.html.erb
  app/views/drivers/show.html.erb
  app/views/drivers/show.json.jbuilder
  config/routes.rb
  db/.DS_Store
  db/migrate/20250221213851_create_drivers.rb
  db/seed_data.rb
  db/seeds.rb
Labels: points: 1, ⚠️ migration required, 🏗️ infrastructure

#27 Migrated ride data and created routes and controller logic
  app/controllers/rides_controller.rb
  app/helpers/ride_helper.rb
  app/models/ride.rb
  app/views/rides/_form.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/index.html.erb
  app/views/rides/new.html.erb
  app/views/rides/show.html.erb
  config/routes.rb
  db/fake_rides_data.csv
  db/migrate/20250224022846_createrides.rb
  db/schema.rb
  features/homepage.feature
  lib/tasks/import_fake_rides.rake
Labels: points: 1, ⚠️ migration required, 🏗️ infrastructure

#34 16 UI passenger view and controller
  app/controllers/passengers_controller.rb
  app/helpers/passengers_helper.rb
  app/javascript/application.js
  app/views/layouts/application.html.erb
  app/views/passengers/_form.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/passengers/_passenger.json.jbuilder
  app/views/passengers/edit.html.erb
  app/views/passengers/index.html.erb
  app/views/passengers/index.json.jbuilder
  app/views/passengers/new.html.erb
  app/views/passengers/show.html.erb
  app/views/passengers/show.json.jbuilder
  config/routes.rb
  features/step_definitions/homepage_steps.rb
Labels: enhancement, points: 1

#36 Added Codecov and codeclimate test reporting
  .github/workflows/ci.yml
  Gemfile
  Gemfile.lock
  features/support/env.rb
  spec/models/dummy_spec.rb
  spec/rails_helper.rb
Labels: points: 1, chore
