Repository cs169/lamorinda-spirit-van, pull requests merged in 2025-05, with the labels that each got.

#132 updated msft keys
  config/credentials.yml.enc
  config/initializers/devise.rb
Labels: enhancement

#126 102 UI driver mobile UI 20
  app/assets/stylesheets/application.css
  app/assets/stylesheets/drivers.css
  app/assets/stylesheets/rides.css
  app/assets/stylesheets/shifts.css
  app/controllers/application_controller.rb
  app/controllers/drivers_controller.rb
  app/controllers/feedbacks_controller.rb
  app/controllers/shifts_controller.rb
  app/views/drivers/_driver.html.erb
  app/views/drivers/index.html.erb
  app/views/drivers/show.html.erb
  app/views/drivers/today.html.erb
  app/views/feedbacks/_form.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/rides/show.html.erb
  app/views/shifts/feedback.html.erb
  app/views/shifts/index.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  config/routes.rb
  features/driver/driver_shift_navigation.feature
  features/step_definitions/driver_shift_steps.rb
  features/support/paths.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
Labels: enhancement, points: 1, 👀 accessibility

#123 103 feat shift calendar autofilling repeated shifts
  .github/workflows/ci.yml
  .simplecov
  app/controllers/shift_templates_controller.rb
  app/controllers/shifts_controller.rb
  app/helpers/shift_templates_helper.rb
  app/models/shift.rb
  app/models/shift_template.rb
  app/views/shift_templates/_form.html.erb
  app/views/shift_templates/_index.html.erb
  app/views/shift_templates/_shift_template.html.erb
  app/views/shift_templates/_shift_template.json.jbuilder
  app/views/shift_templates/edit.html.erb
  app/views/shift_templates/index.json.jbuilder
  app/views/shift_templates/new.html.erb
  app/views/shift_templates/show.html.erb
  app/views/shift_templates/show.json.jbuilder
  app/views/shifts/index.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  config/application.rb
  config/routes.rb
  db/migrate/20250410235915_create_shift_templates.rb
  db/schema.rb
  features/clear_shifts.feature
  features/new_ride_autocomplete.feature
  features/shift_template.feature
  features/step_definitions/dispatcher_shift_steps.rb
  features/step_definitions/factory_steps.rb
  features/step_definitions/shift_template_steps.rb
  features/step_definitions/time_steps.rb
  features/step_definitions/user_authentication_steps.rb
  features/support/env.rb
  spec/controllers/shift_template_controller_spec.rb
  spec/factories/shift_templates.rb
  spec/models/shift_spec.rb
  spec/rails_helper.rb
Labels: enhancement, points: 2, ⚠️ migration required

#129 129 Edit passenger views and divided contents, added quick fare selection…
  app/views/passengers/_form.html.erb
  app/views/rides/edit.html.erb
Labels: enhancement, points: 1

#138 replace Date.today to Time.zone.today, rewrite some tests
  app/controllers/shifts_controller.rb
  app/models/ride.rb
  db/seeds.rb
  features/step_definitions/driver_shift_steps.rb
  spec/controllers/drivers_controller_spec.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/models/passenger_spec.rb
  spec/models/ride_spec.rb
  spec/models/shift_spec.rb
Labels: enhancement, points: 1

#139 fix line break on timeline
  app/views/drivers/today.html.erb
Labels: bug, points: 1

#141 130 more compact datatables truncate long fields column reordering
  app/javascript/datatables.js
  app/views/layouts/application.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/rides/_ride.html.erb
Labels: points: 1, chore

#125 98 rides have link to next ride
  app/controllers/drivers_controller.rb
  app/controllers/passengers_controller.rb
  app/controllers/rides_controller.rb
  app/controllers/shifts_controller.rb
  app/javascript/add_stop.js
  app/javascript/application.js
  app/javascript/autocomplete.js
  app/javascript/datatables.js
  app/models/address.rb
  app/models/ride.rb
  app/views/drivers/today.html.erb
  app/views/passengers/_form.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/_stop_fields.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/filter.html.erb
  app/views/rides/new.html.erb
  app/views/rides/show.html.erb
  app/views/shifts/_shift_rides.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  blazer_queries.yml
  config/routes.rb
  db/migrate/20250418014022_add_next_ride_to_rides.rb
  db/schema.rb
  features/crud_passengers.feature
  features/driver/driver_shift_navigation.feature
  spec/controllers/rides_controller_spec.rb
  spec/factories/passengers.rb
  spec/factories/rides.rb
  spec/models/passenger_spec.rb
  spec/models/ride_spec.rb
Labels: enhancement, points: 2, ⚠️ migration required
