Repository cs169/lamorinda-spirit-van, pull requests merged in 2025-03, with the labels that each got.

#37 31 UI add a home page
  Gemfile
  Gemfile.lock
  app/controllers/rides_controller.rb
  app/models/ride.rb
  app/views/drivers/index.html.erb
  app/views/passengers/index.html.erb
  app/views/rides/filter.html.erb
  config/application.rb
  config/routes.rb
  db/fake_rides_data.csv
  db/seed_data.rb
  spec/controllers/rides_controller_spec.rb
  spec/models/ride_spec.rb
Labels: enhancement, points: 1

#38 22 style incorporate bootstrap css
  app/assets/stylesheets/application.css
  app/assets/stylesheets/drivers.css
  app/controllers/rides_controller.rb
  app/javascript/application.js
  app/models/driver.rb
  app/views/drivers/_driver.html.erb
  app/views/drivers/_form.html.erb
  app/views/drivers/edit.html.erb
  app/views/drivers/index.html.erb
  app/views/drivers/new.html.erb
  app/views/passengers/_form.html.erb
  app/views/passengers/_passenger.html.erb
  app/views/passengers/edit.html.erb
  app/views/passengers/index.html.erb
  app/views/passengers/new.html.erb
  app/views/rides/_form.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/filter.html.erb
  app/views/rides/index.html.erb
  app/views/rides/new.html.erb
  features/homepage.feature
  spec/controllers/rides_controller_spec.rb
Labels: enhancement, points: 1

#66 40 structure create shift model
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/shifts.css
  app/controllers/shifts_controller.rb
  app/helpers/shifts_helper.rb
  app/models/driver.rb
  app/models/shift.rb
  app/views/drivers/_driver.html.erb
  app/views/drivers/_driver.json.jbuilder
  app/views/rides/filter.html.erb
  app/views/shifts/_form.html.erb
  app/views/shifts/_shift.html.erb
  app/views/shifts/_shift.json.jbuilder
  app/views/shifts/edit.html.erb
  app/views/shifts/index.html.erb
  app/views/shifts/index.json.jbuilder
  app/views/shifts/new.html.erb
  app/views/shifts/show.html.erb
  app/views/shifts/show.json.jbuilder
  app/views/simple_calendar/_calendar.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  app/views/simple_calendar/_week_calendar.html.erb
  config/routes.rb
  db/migrate/20250221213851_create_drivers.rb
  db/migrate/20250306215503_create_shifts.rb
  db/migrate/20250306220111_add_driver_to_shifts.rb
  db/schema.rb
  db/seed_data.rb
  spec/controllers/rides_controller_spec.rb
  spec/controllers/shifts_controller_spec.rb
  spec/models/ride_spec.rb
  spec/models/shift_spec.rb
Labels: points: 1, ⚠️ migration required, 🏗️ infrastructure

#39 23 feat filtering for ride table
  app/assets/stylesheets/rides.css
  app/controllers/rides_controller.rb
  app/models/ride.rb
  app/views/rides/_form.html.erb
  app/views/rides/_ride.html.erb
  app/views/rides/edit.html.erb
  app/views/rides/filter.html.erb
  app/views/rides/index.html.erb
  app/views/rides/new.html.erb
  app/views/rides/today.html.erb
  config/routes.rb
  spec/controllers/rides_controller_spec.rb
  spec/models/ride_spec.rb
Labels: enhancement, points: 2

#67 53 feat dispatcher assign shifts page calendar style
  app/controllers/shifts_controller.rb
  app/views/shifts/_form.html.erb
  app/views/shifts/index.html.erb
  app/views/shifts/new.html.erb
  config/routes.rb
  spec/controllers/shifts_controller_spec.rb
Labels: enhancement, points: 1, 💡research needed

#69 Fixed rides schema and migration
  app/views/rides/show.json.jbuilder
  db/dont_use_fake_rides_data.csv
  db/fake_rides_data.csv
  db/migrate/20250224022846_createrides.rb
  db/schema.rb
  lib/tasks/import_fake_data.rake
Labels: points: 1, ⚠️ migration required, chore
